version: "3.8"

services:
  pg:
    image: postgres
    ports:
      - 5555:5432
    environment:
      - "POSTGRES_PASSWORD=123"
      - "POSTGRES_USER=postgres"
      - "POSTGRES_DB=escola"
    volumes:
      - ./postgres:/var/lib/postgresql/data

