version: "3.8"

services:
  pg:
    image: postgres
    ports:
      - 5555:5432
    environment:
      - "POSTGRES_PASSWORD=uv-RRbf2"
      - "POSTGRES_USER=postgres"
      - "POSTGRES_DB=escola"
    volumes:
      - pg-data:/var/lib/postgresql/data
volumes:
  pg-data:
